#% text_encoding = iso8859_1

:title                Test Runner
:failures                 Failures
:test_hierarchy           Test Hierarchy
:finished                 Finished:  #1  seconds
:running                  Running  #1
:interrupted              Interrupted
:run                      Run
:stop                     Stop
:reload_classes           Reload classes every run
:run_test             Run
:runs_counter         Tests: #1
:errors_counter       Errors: #1
:failures_counter     Failures: #1
:not_available            Not available yet.
:clear                    Clear
:quit                     Quit
:kill_thread              Kill test thread
:help                     Help
:test_class_name          Test class name:
:ok                       Ok

:results         Results:
:clear_tooltip        Clear the Results Window and Count Fields and Reset All Success Indicators
:load                 Load module
:no_failures          No failures
:loading_module       Loading module #1 complete
:refresh              Refresh
:progress             Progress
:interrupt            Interrupt
:undeclared_tests     Undeclared Tests
:interrupt_tooltip    Interrupt the Test Run
:load_tooltip         Load the Selected Module
:reset_tooltip       		Reset all components of this Interface Including test priority
:refresh_tooltip      		Refresh all components of this Interface
:toggle_autorun				Run on Compile?
:toggle_autorun_tooltip		Automatically run selected tests when files are compiled
:load_test_modules			Load Test Modules
:load_test_modules_tooltip	Load Test Modules targetting loaded modules
:add_target_modules			Add Target Modules to Coverage
:add_target_modules_tooltip	Add Target Modules to Coverage Harness
:edit_method          Edit method
:edit_method_tooltip  Edit the Selected Test
:run_test_tooltip     Run the Selected Tests
:view_traceback_tooltip  View the Selected Traceback
:view_traceback          View Traceback
