#% text_encoding = iso8859_1

:title               :en_gb Test Runner
:failures          :en_gb       Failures
:test_hierarchy    :en_gb       Test Hierarchy
:finished          :en_gb       Finished:  #1  seconds
:running           :en_gb       Running  #1
:interrupted       :en_gb       Interrupted
:run               :en_gb       Run
:stop              :en_gb       Stop
:reload_classes    :en_gb       Reload classes every run
:run_test            :en_gb Run
:runs_counter        :en_gb Tests: #1
:errors_counter      :en_gb Errors: #1
:failures_counter    :en_gb Failures: #1
:not_available     :en_gb       Not available yet.
:clear             :en_gb       Clear
:quit              :en_gb       Quit
:kill_thread       :en_gb       Kill test thread
:help              :en_gb       Help
:test_class_name   :en_gb       Test class name:
:ok                :en_gb       Ok

:results        :en_gb Results:
:clear_tooltip       :en_gb Clear the Results Window and Count Fields and Reset All Success Indicators
:load                :en_gb Load module
:no_failures         :en_gb No failures
:loading_module      :en_gb Loading module #1 complete
:refresh             :en_gb Refresh
:progress            :en_gb Progress
:interrupt           :en_gb Interrupt
:undeclared_tests    :en_gb Undeclared Tests
:interrupt_tooltip   :en_gb Interrupt the Test Run
:load_tooltip        :en_gb Load the Selected Module
:reset_tooltip       :en_gb Reset the Success Indicator for Selected Tests
:refresh_tooltip     :en_gb Refresh the Test Tree to Show New Tests
:edit_method         :en_gb Edit method
:edit_method_tooltip :en_gb Edit the Selected Test
:run_test_tooltip    :en_gb Run the Selected Tests
:view_traceback_tooltip :en_gb View the Selected Traceback
:view_traceback         :en_gb View Traceback
